name: Index
title: null
remote_theme: jekyll/minima
minima:
  skin: dark
  date_format: "%b %-d, %Y"
plugins:
  - jekyll-relative-links
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
relative_links:
  enabled: true
  collections: true
include:
  - README.md
